### ISSUE TITLE
How to get the upper bound in the paper?

### ISSUE THREAD

**Issue by XZhang00** [tomhosking/hrq-vae#10]
I want to know how to generate sentences using the sketch of selected exemplar. In other words, where can I get the oracle sketch of selected exemplar? Looking forward to your reply.

**Comment by tomhosking** [comment]
Hi, the code that runs the oracle evaluation is here:
https://github.com/tomhosking/torchseq/blob/main/torchseq/metric_hooks/sep_ae.py#L127

The important parts are to make sure `infer_codes` in the config is set to `False`:
`agent.config.bottleneck.code_predictor.data["infer_codes"] = False`

Then, perform inference on your evaluation dataset with a field_map like below, where `syn_input` is set to one of the references:
```
config_gen_with_templ["json_dataset"] = {
          "path": config.eval.metrics.sep_ae.eval_dataset,
          "field_map": [
              {"type": "copy", "from": "tgt", "to": "target"},
              {"type": "copy", "from": "syn_input", "to": "template"},
              {"type": "copy", "from": "sem_input", "to": "source"},
          ],
      }
```

This will make the model extract the semantics from the input, but use the syntactic sketch from the target output.

If you're just trying to replicate the scores, you should be able to run inference with a pre-trained checkpoint (see the readme) and then check `metrics.test.json` for the oracle results.

**Comment by XZhang00** [comment]
site-packages/torchseq/datasets/json_dataset.py", line 119, in to_tensor
    sample[f["to"]] = JsonDataset._transform(obj[f["from"]], f.get("type", "copy"))
KeyError: 'tgt'

I just tried but i ran into this problem, how can i fix this?

**Comment by tomhosking** [comment]
That looks like you're using the latest version of torchseq - please follow the instructions in the readme and use v2.3.1.

**Comment by XZhang00** [comment]
Thanks for your quick reply, I have solved the problem!
