### ISSUE TITLE
how to train for other language?

### ISSUE THREAD

**Issue by AliRezaSafaei9494** [tomhosking/hrq-vae#11]
hi, thanks  for such great repo
i already create dataset for my target languag like wikianswers-triples-chunk-extendstop-realexemplars-resample-drop30-N5-R100
and put it in data folder.
for second stage i nead bert-base-multilingual-uncased.embeddings.pt
how can i achive to this?

i already test it :
############################################################
from transformers import BertModel, BertTokenizer, BertConfig
import torch

enc = BertTokenizer.from_pretrained("bert-base-multilingual-uncased")

text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = enc.tokenize(text)

masked_index = 8
tokenized_text[masked_index] = '[MASK]'
indexed_tokens = enc.convert_tokens_to_ids(tokenized_text)
segments_ids = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
dummy_input = [tokens_tensor, segments_tensors]

model = BertModel.from_pretrained("bert-base-multilingual-cased", torchscript=True)

traced_model = torch.jit.trace(model, [tokens_tensor, segments_tensors])
torch.jit.save(traced_model, "bert-base-multilingual-uncased.embeddings.pt")
############################################

but got error:
/root/anaconda3/envs/hrq/lib/python3.7/site-packages/torch/serialization.py:781: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "/root/anaconda3/envs/hrq/bin/torchseq", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/hrq/lib/python3.7/site-packages/torchseq/main.py", line 110, in main
    use_cuda=(not args.cpu),
  File "/root/anaconda3/envs/hrq/lib/python3.7/site-packages/torchseq/agents/para_agent.py", line 65, in __init__
    self.model = BottleneckAutoencoderModel(self.config, src_field=self.src_field)
  File "/root/anaconda3/envs/hrq/lib/python3.7/site-packages/torchseq/models/bottleneck_autoencoder.py", line 35, in __init__
    self.seq_encoder = SequenceEncoder(config)
  File "/root/anaconda3/envs/hrq/lib/python3.7/site-packages/torchseq/models/encoder.py", line 24, in __init__
    self.embeddings.weight.data = Tokenizer().get_embeddings(config.prepro.tokenizer)
TypeError: Variable data has to be a tensor, but got RecursiveScriptModule

**Comment by tomhosking** [comment]
Hi, you just need the token embeddings for that model, which you can access like:
```
from transformers import BertModel
import torch

model = BertModel.from_pretrained("bert-base-multilingual-cased")

torch.save(model.embeddings.word_embeddings.weight.data, './data/pretrained-vocabs/bert-base-multilingual-uncased.embeddings.pt')
```

Hopefully that works!
