### ISSUE TITLE
Lower performance with trained model

### ISSUE THREAD

**Issue by hahally** [tomhosking/hrq-vae#7]
Hi, my problem also is here https://github.com/L-Zhe/BTmPG/issues/2.
On MSCOCO data, The model‘s performance is not good. BLEU 8.79, self-BLEU: 18.56.
Could you please tell me some tricks to train the model on MSCOCO data? 
Thanks!

**Comment by tomhosking** [comment]
Can I check that you're trying to train HRQ-VAE on MSCOCO, not BTmPG? What steps are you taking to train the model, and how are you evaluating the results? 

The results I report in the HRQ-VAE paper are based on selecting one of the five captions as input, and comparing the generated paraphrase to the other four captions - if you only compare to one caption, then the scores will be lower. But, I didn't require any additional tricks for MSCOCO and the hyperparameters were the same as for the other two datasets reported in the paper.

**Comment by hahally** [comment]
I am training BTmPG on MSCOCO now.

**Comment by tomhosking** [comment]
I am not the author of BTmPG and cannot help with any problems you have with that model, sorry.

**Comment by hahally** [comment]
Sorry to bother you.
I have read your paper. I saw you compared BTMPG.
Thanks again.
