### ISSUE TITLE
'Config' object has no attribute 'encoder_outputs'

### ISSUE THREAD

**Issue by hahally** [tomhosking/hrq-vae#8]
Hello!!
When I use the checkpoint model and load the config file, it shows no attribute 'encoder_outputs'?!

**Comment by hahally** [comment]
![image](https://user-images.githubusercontent.com/47556859/199059933-7e073536-d3a9-4720-91db-9bfe0a1c5ffe.png)

**Comment by tomhosking** [comment]
Hi, what code are you using to run the model? It looks like it's using an AQAgent, which is for question generation, not paraphrasing.

**Comment by hahally** [comment]
Hi, if paraphrasing, I can't find the para_agent. So, how can I execute paraphrasing?

**Comment by hahally** [comment]
what torchseq version do I pick for hrq-vae?

**Comment by tomhosking** [comment]
Please follow the installation instructions in [the readme](https://github.com/tomhosking/hrq-vae#installation) - you should install TorchSeq from the `v2.3.1` github release, `pip install git+https://github.com/tomhosking/torchseq.git@v2.3.1`.

**Comment by hahally** [comment]
Ok, Thank you! I got it!!!

**Comment by tomhosking** [comment]
Great :)
